// AUTO-GENERATED by `scripts/codegen-plugin-barrels.ts`. DO NOT EDIT.
// Run `yarn plugins:codegen` after adding/removing/renaming a plugin.

import type { ServerPluginBinding } from "../server-bindings-types";
import { mcpBinding } from "../server-bindings-types";

import accountingDef from "../accounting/definition";
import canvasDef from "../canvas/definition";
import chartDef from "../chart/definition";
import manageSkillsDef from "../manageSkills/definition";
import markdownDef from "../markdown/definition";
import photoLocationsDef from "../photoLocations/definition";
import presentCollectionDef from "../presentCollection/definition";
import presentFormDef from "../presentForm/definition";
import presentHtmlDef from "../presentHtml/definition";
import presentMulmoScriptDef from "../presentMulmoScript/definition";
import presentSVGDef from "../presentSVG/definition";
import presentShapeScriptDef from "../presentShapeScript/definition";
import schedulerAutomationsDef from "../scheduler/automationsDefinition";
import spreadsheetDef from "../spreadsheet/definition";
import { META as accountingMeta } from "../accounting/meta";
import { META as canvasMeta } from "../canvas/meta";
import { META as chartMeta } from "../chart/meta";
import { META as manageSkillsMeta } from "../manageSkills/meta";
import { META as markdownMeta } from "../markdown/meta";
import { META as photoLocationsMeta } from "../photoLocations/meta";
import { META as presentCollectionMeta } from "../presentCollection/meta";
import { META as presentFormMeta } from "../presentForm/meta";
import { META as presentHtmlMeta } from "../presentHtml/meta";
import { META as presentMulmoScriptMeta } from "../presentMulmoScript/meta";
import { META as presentSVGMeta } from "../presentSVG/meta";
import { META as presentShapeScriptMeta } from "../presentShapeScript/meta";
import { META as schedulerAutomationsMeta } from "../scheduler/automationsMeta";
import { META as spreadsheetMeta } from "../spreadsheet/meta";

/** All plugin MCP bindings the codegen discovered for plugins whose META declares
 *  both `apiNamespace` and `mcpDispatch`. Plugins without those fields (image plugins,
 *  external npm plugins) live in `_extras.ts`. Combined inside `src/plugins/server.ts`. */
export const GENERATED_SERVER_BINDINGS: readonly ServerPluginBinding[] = [
  mcpBinding(accountingDef, accountingMeta),
  mcpBinding(canvasDef, canvasMeta),
  mcpBinding(chartDef, chartMeta),
  mcpBinding(manageSkillsDef, manageSkillsMeta),
  mcpBinding(markdownDef, markdownMeta),
  mcpBinding(photoLocationsDef, photoLocationsMeta),
  mcpBinding(presentCollectionDef, presentCollectionMeta),
  mcpBinding(presentFormDef, presentFormMeta),
  mcpBinding(presentHtmlDef, presentHtmlMeta),
  mcpBinding(presentMulmoScriptDef, presentMulmoScriptMeta),
  mcpBinding(presentSVGDef, presentSVGMeta),
  mcpBinding(presentShapeScriptDef, presentShapeScriptMeta),
  mcpBinding(schedulerAutomationsDef, schedulerAutomationsMeta),
  mcpBinding(spreadsheetDef, spreadsheetMeta),
];
